# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# asdfasdfa.py
# Created on: 2018-12-19 10:53:59.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
KentonParcels_id = "ID\\KentonParcels_id"
KentonParcels_id__2_ = KentonParcels_id
KentonParcels_id__6_ = KentonParcels_id
KentonParcels_id__4_ = "ID\\KentonParcels_id"
KentonParcels_id__5_ = KentonParcels_id__4_

# Process: Calculate Field
arcpy.CalculateField_management(KentonParcels_id, "avg_std_01", "( !avg_std! - 10) / (110 - 10)", "PYTHON_9.3", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(KentonParcels_id__4_, "g_scr_01", "( !g_score! - 10) / (110 - 10)", "PYTHON_9.3", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(KentonParcels_id, "comp_01", "!avg_std_01! + !g_scr_01!", "PYTHON_9.3", "")

