# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# adfasdf.py
# Created on: 2018-12-19 10:37:11.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


inp = arcpy.GetParameterAsText(0)

# Local variables:
KentonParcels_id = "ID\\KentonParcels_id"
sum = "in_memory\\sum"

field_names = [f.name for f in arcpy.ListFields(inp)]

for f in ['avg_std_01', 'g_scr_01', 'comp_01']:
    if f not in field_names:
        arcpy.AddField_management(inp, f, "DOUBLE")


# Process: Summary Statistics
arcpy.Statistics_analysis(inp, sum, "avg_std MIN;avg_std MAX;g_score MIN;g_score MAX", "")

srch = arcpy.SearchCursor(sum)

r = next(srch)

min_std =  r.getValue('MIN_avg_std')
max_std =  r.getValue('MAX_avg_std')
min_g =  r.getValue('MIN_g_score')
max_g =  r.getValue('MAX_g_score')

del r, srch



# Process: Calculate Field
arcpy.CalculateField_management(
    inp,
    "avg_std_01",
    "round((!avg_std! - {min}) / ({max} - {min}), 2)".format(min=min_std, max=max_std),
    "PYTHON_9.3"
)

# Process: Calculate Field (2)
arcpy.CalculateField_management(
    inp,
    "g_scr_01",
    "round((!g_score! - {min}) / ({max} - {min}), 2)".format(min=min_g, max=max_g),
    "PYTHON_9.3"
)

# Process: Calculate Field (3)
arcpy.CalculateField_management(inp, "comp_01", "!avg_std_01! - !g_scr_01!", "PYTHON_9.3", "")


arcpy.SetParameterAsText(1, inp)
