# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# round_vals.py
# Created on: 2018-12-19 10:13:04.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


inp = arcpy.GetParameterAsText(0)


for f in ['acre', 'zone_min', 'zone_max', 'zone_avg', 'red_std', 'red_avg', 'grn_std', 'grn_avg',
          'blu_std', 'blu_avg', 'avg_std', 'g_score']:
    arcpy.CalculateField_management(
        inp,
        f,
        "round(!{0}!, 1)".format(f),
        "PYTHON_9.3",
        ""
    )

arcpy.SetParameterAsText(1, inp)
